# configuration for https://travis-ci.org/jestevez/onixcoinj-gui
sudo: false
language: java
jdk: oraclejdk8
install: true # remove default
script:
  - jdk_switcher use openjdk7
  - cd onixcoinj-gui
  - mvn -q clean package -Pno-network  
  
